#!/bin/sh

echo "pre-commit: About to run the checkstyle linter..."
echo
mvn checkstyle:checkstyle
echo

file=$(<target/checkstyle-result.xml)


input="target/checkstyle-result.xml"
errors=false
while IFS= read -r line
do
  if [[ "$line" == *"<error"* ]]; then
  	errors=true
  	endSubstring=$(awk -v a="$line" -v b=" source" 'BEGIN{print index(a,b)}')
    echo "$line" | cut -b 2-$endSubstring
  fi
done < "$input"

if [ "$errors" = true ]; 
then
	echo ""
	echo "Please fix the above errors"
	echo ""
	exit 1
else
	echo "No errors found"
	exit 0
fi